# AI-Studio 默认配置
GLOBAL_AUTO_OPEN_BROWSER=true
GLOBAL_LOG_LEVEL=1
GLOBAL_PROXY=
GLOBAL_HF_MIRROR=https://hf-mirror.com
GLOBAL_PIP_MIRROR=https://pypi.tuna.tsinghua.edu.cn/simple
GLOBAL_NPM_MIRROR=https://registry.npmmirror.com
OPEN_WEBUI_PORT=3000
SILLYTAVERN_PORT=8000
COMFYUI_PORT=8188
MLX_VIDEO_PORT=7860
BROWSER_USE_PORT=9222
FAZM_PORT=8501
OLLAMA_HOST=http://localhost:11434
